### ISSUE TITLE
Misspellings in "Don't fear the grepper!" documents

### ISSUE THREAD

**Issue by antononcube** [lizmat/articles#1]
Here are a few misspellings I think should be corrected:

Programmming : Programming
instalment : installment
explicitely : explicitly

Not sure about this:
listiness : list-ness

**Comment by lizmat** [comment]
Thanks for the feedback!

Programmming: fixed
Explicitely: fixed

Instalment is valid British spelling afaik.

Listiness is a made up word, in conjunction with Raku.

**Comment by antononcube** [comment]
> Instalment is valid British spelling afaik.

Ok. I was careful not to report "behaviour" and "flavours". :)
